using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using YazGel.Models;

namespace YazGel
{
    public class CreatePdf
    {
        Context cdb = new Context();
        int toplamSutun = 2;
        Document document;
        Font fontStyle;
        PdfPTable pdfTable = new PdfPTable(2);
        PdfPCell pdfPCell;
        MemoryStream memoryStream = new MemoryStream();
        List<Internship> internship = new List<Internship>();


        public byte[] Pdf([Bind] Internship intern)
        {

            var interns = cdb.Internships.OrderByDescending(o => o.Id).Where(s => s.Id == intern.Id).ToList();

            internship = interns;
            document = new Document(PageSize.A4, 0f, 0f, 0f, 0f);
            document.SetPageSize(PageSize.A4);
            document.SetMargins(25f, 25f, 10f, 10f);
            pdfTable.WidthPercentage = 100;
            pdfTable.HorizontalAlignment = Element.ALIGN_LEFT;
            fontStyle = FontFactory.GetFont("Times New Roman" ,11f, 1);
            PdfWriter.GetInstance(document, memoryStream);
            document.Open();
            pdfTable.SetWidths(new float[] { 40f, 120f });

            //document.Add(png);
            this.PdfHeader();
            this.PdfBody();

            pdfTable.HeaderRows = 1;
            document.Add(pdfTable);
            document.Close();
            return memoryStream.ToArray();
        }

        public void PdfHeader()
        {
            DateTime today = new DateTime();
            today = DateTime.Now.ToLocalTime();
            fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
            pdfPCell = new PdfPCell(new Phrase(" T.C.\nKOCAELI UNIVERSITESI\nTEKNOLOJI FAKULTESI\n(Staj Basvuru ve Kabul Formu)\n\n\n\nILGILI MAKAMA", fontStyle));
            pdfPCell.Colspan = 2;
            pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
            pdfPCell.Border = 0;
            pdfPCell.BackgroundColor = BaseColor.WHITE;
            pdfPCell.ExtraParagraphSpace = 5;
            pdfTable.AddCell(pdfPCell);
            pdfTable.CompleteRow();

            fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
            pdfPCell = new PdfPCell(new Phrase("Tarih: "+today , fontStyle));
            pdfPCell.Colspan = 2;
            pdfPCell.HorizontalAlignment = Element.ALIGN_RIGHT;
            pdfPCell.Border = 0;
            pdfPCell.BackgroundColor = BaseColor.WHITE;
            pdfPCell.ExtraParagraphSpace = 5;
            pdfTable.AddCell(pdfPCell);
            pdfTable.CompleteRow();

            fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
            pdfPCell = new PdfPCell(new Phrase(" Teknoloji Fakültesi ........ Mühendisliği Bölümü ......... numaralı öğrencisiyim. Kurumunuzda staj yapmamın uygun görülmesi halinde bu formun alttaki kısmını doldurularak fakültemiz ilgili bölüm başkanlığına gönderilmesini saygılarımla arz ederim. İşyeri uygulaması süresi içerisinde alınan rapor, istirahat vb.belgelerin aslını alınan gün içerisinde bölüm başkanlığına bildireceğimi beyan ve taahhüt ederim.", fontStyle));
            pdfPCell.Colspan = 2;
            pdfPCell.HorizontalAlignment = Element.ALIGN_LEFT;
            pdfPCell.Border = 0;
            pdfPCell.BackgroundColor = BaseColor.WHITE;
            pdfPCell.ExtraParagraphSpace = 5;
            pdfTable.AddCell(pdfPCell);
            pdfTable.CompleteRow();

            fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
            pdfPCell = new PdfPCell(new Phrase(" İşyeri uygulaması süresi içerisinde alınan rapor, istirahat vb.belgelerin aslını alınan gün içerisinde bölüm başkanlığına bildireceğimi beyan ve taahhüt ederim.", fontStyle));
            pdfPCell.Colspan = 2;
            pdfPCell.HorizontalAlignment = Element.ALIGN_LEFT;
            pdfPCell.Border = 0;
            pdfPCell.BackgroundColor = BaseColor.WHITE;
            pdfPCell.ExtraParagraphSpace = 5;
            pdfTable.AddCell(pdfPCell);
            pdfTable.CompleteRow();
        }
        public void PdfBody()
        {
            fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);

            foreach (var stn in internship)
            {
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Ad", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.Name, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Soyad", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.Surname, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Kimilk No", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.TC, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Telefon Numarasi", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.PhoneNumber, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("E-Posta", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.Mail, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Adres", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.Address, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 10f, 1);
                pdfPCell = new PdfPCell(new Phrase("", fontStyle));
                pdfPCell.Rowspan = 1;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);

                pdfPCell = new PdfPCell(new Phrase("Staj Bilgileri", fontStyle));
                pdfPCell.Rowspan = 1;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Yapılacak Staj/IME", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase("Staj 1", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Baslama Tarihi", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.Start, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Bitis Tarihi", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.EndDate, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("SSK", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.SSK.ToString(), fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Genel Saglik Sigortasi", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.GSS.ToString(), fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("25 yasini doldurdum", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.Age.ToString(), fontStyle)); ;
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 10f, 1);
                pdfPCell = new PdfPCell(new Phrase("", fontStyle));
                pdfPCell.Rowspan = 1;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);

                pdfPCell = new PdfPCell(new Phrase("Firma Bilgileri", fontStyle));
                pdfPCell.Rowspan = 1;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Firma Adi", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.ComName, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Faaliyet Alani", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.ComBuss, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Firma Adresi", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.ComAddress, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Telefon", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.ComPhoneNumber, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("E-Posta", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.ComMail, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("Yetkili Kişi", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase(stn.ComAdmin, fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();
                pdfTable.CompleteRow();
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 1);
                pdfPCell = new PdfPCell(new Phrase("İmza", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                fontStyle = FontFactory.GetFont("Times New Roman", 9f, 0);
                pdfPCell = new PdfPCell(new Phrase("", fontStyle));
                pdfPCell.Rowspan = toplamSutun;
                pdfPCell.HorizontalAlignment = Element.ALIGN_CENTER;
                pdfPCell.VerticalAlignment = Element.ALIGN_MIDDLE;
                pdfPCell.BackgroundColor = BaseColor.WHITE;
                pdfTable.AddCell(pdfPCell);
                pdfTable.CompleteRow();

            }
        }
    }
}
