// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YazGel.Models;

namespace YazGel.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221029185941_fkTry")]
    partial class fkTry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("YazGel.Models.Committee", b =>
                {
                    b.Property<int>("committeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("committeeId");

                    b.ToTable("Committees");
                });

            modelBuilder.Entity("YazGel.Models.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("roleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("YazGel.Models.Student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<int>("studentGender")
                        .HasColumnType("int");

                    b.Property<string>("studentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentId");

                    b.HasIndex("role");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("YazGel.Models.Supervisor", b =>
                {
                    b.Property<int>("supervisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("supervisorGender")
                        .HasColumnType("int");

                    b.Property<string>("supervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supervisorNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supervisorPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supervisorSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("supervisorId");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("YazGel.Models.Teacher", b =>
                {
                    b.Property<int>("teacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("teacherGender")
                        .HasColumnType("int");

                    b.Property<string>("teacherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacherNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacherPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacherSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("teacherType")
                        .HasColumnType("int");

                    b.HasKey("teacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("YazGel.Models.Student", b =>
                {
                    b.HasOne("YazGel.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
