// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YazGel.Models;

namespace YazGel.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221103235056_DocumentsFix")]
    partial class DocumentsFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("YazGel.Models.DocumentProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ProgressName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentProgress");
                });

            modelBuilder.Entity("YazGel.Models.Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("InternshipBook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternshipId")
                        .HasColumnType("int");

                    b.Property<string>("InternshipScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecourseConfirm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InternshipId");

                    b.HasIndex("StudentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("YazGel.Models.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Age")
                        .HasColumnType("bit");

                    b.Property<string>("ComAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComBuss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GSS")
                        .HasColumnType("bit");

                    b.Property<bool>("Gov")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SSK")
                        .HasColumnType("bit");

                    b.Property<string>("Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Internships");
                });

            modelBuilder.Entity("YazGel.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("YazGel.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DocumentsId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgressId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentsId");

                    b.HasIndex("ProgressId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("role");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("YazGel.Models.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("role");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("YazGel.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Type")
                        .HasColumnType("bit");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("role");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("YazGel.Models.Documents", b =>
                {
                    b.HasOne("YazGel.Models.Internship", "Internship")
                        .WithMany("DocumentId")
                        .HasForeignKey("InternshipId")
                        .IsRequired();

                    b.HasOne("YazGel.Models.Student", "Student")
                        .WithMany("Documents")
                        .HasForeignKey("StudentId")
                        .IsRequired();

                    b.Navigation("Internship");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("YazGel.Models.Internship", b =>
                {
                    b.HasOne("YazGel.Models.Student", null)
                        .WithMany("Internships")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("YazGel.Models.Student", b =>
                {
                    b.HasOne("YazGel.Models.Documents", null)
                        .WithMany("Students")
                        .HasForeignKey("DocumentsId");

                    b.HasOne("YazGel.Models.DocumentProgress", "DocumentProgress")
                        .WithMany("Students")
                        .HasForeignKey("ProgressId");

                    b.HasOne("YazGel.Models.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId");

                    b.HasOne("YazGel.Models.Role", "Role")
                        .WithMany("sId")
                        .HasForeignKey("role")
                        .IsRequired();

                    b.Navigation("DocumentProgress");

                    b.Navigation("Role");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("YazGel.Models.Supervisor", b =>
                {
                    b.HasOne("YazGel.Models.Role", "Role")
                        .WithMany("svId")
                        .HasForeignKey("role")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YazGel.Models.Teacher", b =>
                {
                    b.HasOne("YazGel.Models.Role", "Role")
                        .WithMany("tId")
                        .HasForeignKey("role")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YazGel.Models.DocumentProgress", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("YazGel.Models.Documents", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("YazGel.Models.Internship", b =>
                {
                    b.Navigation("DocumentId");
                });

            modelBuilder.Entity("YazGel.Models.Role", b =>
                {
                    b.Navigation("sId");

                    b.Navigation("svId");

                    b.Navigation("tId");
                });

            modelBuilder.Entity("YazGel.Models.Student", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Internships");
                });

            modelBuilder.Entity("YazGel.Models.Teacher", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
