// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YazGel.Models;

namespace YazGel.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("YazGel.Models.Committee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<int>("teacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("role");

                    b.ToTable("Committees");
                });

            modelBuilder.Entity("YazGel.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("YazGel.Models.Student", b =>
                {
                    b.Property<int>("tId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("tId");

                    b.HasIndex("role");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("YazGel.Models.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("role");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("YazGel.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Type")
                        .HasColumnType("bit");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("role");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("YazGel.Models.Committee", b =>
                {
                    b.HasOne("YazGel.Models.Teacher", "tId")
                        .WithMany("tId")
                        .HasForeignKey("Id")
                        .IsRequired();

                    b.HasOne("YazGel.Models.Role", "Role")
                        .WithMany("cId")
                        .HasForeignKey("role")
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("tId");
                });

            modelBuilder.Entity("YazGel.Models.Student", b =>
                {
                    b.HasOne("YazGel.Models.Role", "Role")
                        .WithMany("sId")
                        .HasForeignKey("role")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YazGel.Models.Supervisor", b =>
                {
                    b.HasOne("YazGel.Models.Role", "Role")
                        .WithMany("svId")
                        .HasForeignKey("role")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YazGel.Models.Teacher", b =>
                {
                    b.HasOne("YazGel.Models.Role", "Role")
                        .WithMany("tId")
                        .HasForeignKey("role")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YazGel.Models.Role", b =>
                {
                    b.Navigation("cId");

                    b.Navigation("sId");

                    b.Navigation("svId");

                    b.Navigation("tId");
                });

            modelBuilder.Entity("YazGel.Models.Teacher", b =>
                {
                    b.Navigation("tId");
                });
#pragma warning restore 612, 618
        }
    }
}
